image: docker:git

services:
- docker:dind

default:
  tags:
    - chataigne

variables:
  ALPINE_VERSION: "3.20"
  ANSIBLE_VERSION: "11.13.0"
  ANSIBLE_LINT_VERSION: "25.12.0"
  MITOGEN_VERSION: "0.3.49"

stages:
- build_image
- test

before_script:
  - mkdir -p ${HOME}/.docker
  - echo ${DOCKER_AUTH_CONFIG} > ${HOME}/.docker/config.json
  - docker login -u "${CI_REGISTRY_USER}" -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"

build_image.default:
  stage: build_image
  script:
  - docker buildx create --driver docker-container --use
  - docker buildx build
    --provenance=false
    --pull
    --push
    --build-arg ALPINE_VERSION="${ALPINE_VERSION}"
    --build-arg ANSIBLE_VERSION="${ANSIBLE_VERSION}"
    --build-arg ANSIBLE_LINT_VERSION="${ANSIBLE_LINT_VERSION}"
    --build-arg MITOGEN_VERSION="${MITOGEN_VERSION}"
    --build-arg BUILD_NAME="${CI_PROJECT_NAME}"
    --build-arg BUILD_DATE="$(date '+%FT%T.%s%z')"
    --build-arg BUILD_VCSREF="${CI_COMMIT_SHA:0:8}"
    --platform=linux/amd64
    -t "${CI_REGISTRY_IMAGE}:${ANSIBLE_VERSION}"
    .
  only:
  - master
  except:
  - tags

build_image.feature:
  stage: build_image
  script:
  - docker buildx create --driver docker-container --use
  - docker buildx build
    --provenance=false
    --pull
    --push
    --build-arg ALPINE_VERSION="${ALPINE_VERSION}"
    --build-arg ANSIBLE_VERSION="${ANSIBLE_VERSION}"
    --build-arg ANSIBLE_LINT_VERSION="${ANSIBLE_LINT_VERSION}"
    --build-arg MITOGEN_VERSION="${MITOGEN_VERSION}"
    --build-arg BUILD_NAME="${CI_PROJECT_NAME}"
    --build-arg BUILD_DATE="$(date '+%FT%T.%s%z')"
    --build-arg BUILD_VCSREF="${CI_COMMIT_SHA:0:8}"
    --platform=linux/amd64
    -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME%%-*}"
    .
  only:
  - "/^[0-9]+-.*$/"
  except:
  - tags

build_image.nonstd:
  stage: build_image
  script:
  - docker buildx create --driver docker-container --use
  - docker buildx build
    --provenance=false
    --pull
    --push
    --build-arg ALPINE_VERSION="${ALPINE_VERSION}"
    --build-arg ANSIBLE_VERSION="${ANSIBLE_VERSION}"
    --build-arg ANSIBLE_LINT_VERSION="${ANSIBLE_LINT_VERSION}"
    --build-arg MITOGEN_VERSION="${MITOGEN_VERSION}"
    --build-arg BUILD_NAME="${CI_PROJECT_NAME}"
    --build-arg BUILD_DATE="$(date '+%FT%T.%s%z')"
    --build-arg BUILD_VCSREF="${CI_COMMIT_SHA:0:8}"
    --platform=linux/amd64
    -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME:0:128}"
    .
  only:
  - "/^[a-zA-Z]+.*$/"
  except:
  - master
  - dev
  - tags

build_image.tag:
  stage: build_image
  script:
  - docker buildx create --driver docker-container --use
  - docker buildx build
    --provenance=false
    --pull
    --build-arg ALPINE_VERSION="${ALPINE_VERSION}"
    --build-arg ANSIBLE_VERSION="${CI_COMMIT_REF_NAME}"
    --build-arg ANSIBLE_LINT_VERSION="${ANSIBLE_LINT_VERSION}"
    --build-arg MITOGEN_VERSION="${MITOGEN_VERSION}"
    --build-arg BUILD_NAME="${CI_PROJECT_NAME}"
    --build-arg BUILD_DATE="$(date '+%FT%T.%s%z')"
    --build-arg BUILD_VCSREF="${CI_COMMIT_SHA:0:8}"
    --platform=linux/arm64,linux/amd64
    --push
    -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"
    -t "${DU_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"
    -t "${CI_REGISTRY_IMAGE}:latest"
    -t "${DU_REGISTRY_IMAGE}:latest"
    .
  only:
  - tags

test_image.default:
  stage: test
  image: "${CI_REGISTRY_IMAGE}:${ANSIBLE_VERSION}"
  before_script: []
  script:
  - ansible --version
  - ansible-lint --version
  - python3 -c "import ansible_mitogen"
  only:
  - master
  except:
  - tags

test_image.feature:
  stage: test
  image: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME%%-*}"
  before_script: []
  script:
  - ansible --version
  - ansible-lint --version
  - python3 -c "import ansible_mitogen"
  only:
  - "/^[0-9]+-.*$/"
  except:
  - tags

test_image.nonstd:
  stage: test
  image: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME:0:128}"
  before_script: []
  script:
  - ansible --version
  - ansible-lint --version
  - python3 -c "import ansible_mitogen"
  only:
  - "/^[a-zA-Z]+.*$/"
  except:
  - master
  - dev
  - tags

test_image.tag:
  stage: test
  image: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"
  before_script: []
  script:
  - ansible --version
  - ansible-lint --version
  - python3 -c "import ansible_mitogen"
  only:
  - tags


